# Generated by Django 4.1.7 on 2023-03-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='rate',
        ),
    ]
